[[permission]]
identifier = "allow-app-commands"
description = "Allow the frontend to use app commands."
commands.allow = [
  "list_project_tree",
  "parse_uml_graph",
  "read_text_file",
  "write_text_file",
  "remove_text_file",
  "export_netbeans_project",
  "add_field_to_class",
  "add_constructor_to_class",
  "add_method_to_class",
  "create_netbeans_project",
  "compile_project",
  "run_main",
  "cancel_run",
  "read_settings",
  "write_settings",
  "ls_start",
  "ls_stop",
  "ls_did_open",
  "ls_did_change",
  "ls_did_close",
  "ls_format_document"
]
